"""Generate the SuperGrid deployment for BlindQuote from deploy/topology.json.

    uv run python deploy/gen_supergrid.py

Writes deploy/compose.supergrid.yaml (six SuperNode containers connecting to
fleet-supergrid.flower.ai) and prints the one-time key + registration commands.
Each container mounts only its own node data, the bureau key and its private key,
and gets its own model provider (Flower for Endeavor, Nebius for Kimi/MiniMax).
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IMAGE = "flwr/supernode:1.39.0"
FLOWER_ENDPOINT = "https://api.flower.ai/v1/responses"

PROVIDER_ENV = {
    None: {"FLWR_MODEL_API_ENDPOINT": FLOWER_ENDPOINT, "FLWR_MODEL_API_KEY": "${FLWR_MODEL_API_KEY}"},
    "flower": {"FLWR_MODEL_API_ENDPOINT": FLOWER_ENDPOINT, "FLWR_MODEL_API_KEY": "${FLWR_MODEL_API_KEY}"},
    "nebius-kimi": {"FLWR_MODEL_API_ENDPOINT": "${NEBIUS_MODEL_API_ENDPOINT}", "FLWR_MODEL_API_KEY": "${NEBIUS_KIMI_API_KEY}"},
    "nebius-minimax": {"FLWR_MODEL_API_ENDPOINT": "${NEBIUS_MODEL_API_ENDPOINT}", "FLWR_MODEL_API_KEY": "${NEBIUS_MINIMAX_API_KEY}"},
}


def node_config(cfg: dict[str, str]) -> str:
    cfg = dict(cfg, data_dir="/data")
    if cfg["role"] in {"bureau", "bank"}:  # only signer and verifiers hold the attestation key
        cfg["hmac_key_file"] = "/secrets/bureau.key"
    return " ".join(f"{k}={json.dumps(str(v))}" for k, v in cfg.items())


def main() -> None:
    nodes = json.loads((ROOT / "deploy" / "topology.json").read_text())["nodes"]
    lines = [
        "# Generated by deploy/gen_supergrid.py from deploy/topology.json - do not edit by hand.",
        "# Run from the repo root:  docker compose -f deploy/compose.supergrid.yaml --env-file .env up",
        "services:",
    ]
    for spec in nodes:
        key = spec["key"]
        lines += [
            f"  {key}:",
            f"    image: {IMAGE}",
            "    command:",
            "      - --superlink=fleet-supergrid.flower.ai:443",
            f"      - --auth-supernode-private-key=/keys/{key}",
            "      - --allow-runtime-dependency-installation",
            f"      - --node-config={node_config(spec['node_config'])}",
            "    environment:",
        ]
        lines += [f"      {k}: \"{v}\"" for k, v in PROVIDER_ENV[spec.get("provider")].items()]
        lines += [
            "    volumes:",
            f"      - ../keys/{key}:/keys/{key}:ro",
            f"      - ../{spec['node_config']['data_dir']}:/data:ro",
        ]
        if spec["node_config"]["role"] in {"bureau", "bank"}:
            lines.append("      - ../secrets:/secrets:ro")
        lines.append("    restart: unless-stopped")
    out = ROOT / "deploy" / "compose.supergrid.yaml"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(ROOT)}\n")

    print("# One-time setup (after `uvx --from flwr==1.39.0 flwr login supergrid`):")
    print("mkdir -p keys")
    for spec in nodes:
        k, cfg = spec["key"], spec["node_config"]
        print(f'ssh-keygen -t ecdsa -b 384 -N "" -C "{k}" -f keys/{k}')
        where = f' --location="{spec["latlon"]}"' if spec.get("latlon") else ""  # borrower stays unlocated
        print(f'uvx --from flwr==1.39.0 flwr supernode register keys/{k}.pub supergrid --name="{cfg["name"]}"{where}')
    print("# Then create a *deployment* federation and add each SuperNode id to it:")
    print("uvx --from flwr==1.39.0 flwr supernode list supergrid --verbose")
    print("uvx --from flwr==1.39.0 flwr federation add-supernode <supernode-id> @<username>/<federation> supergrid")


if __name__ == "__main__":
    main()
